### ISSUE TITLE
Pantone support ?

### ISSUE THREAD

**Issue by pixelastic** [carloscabo/colz#6]
Hello,

I'm currently using your rgb.to website to get hex values from Pantone. I just found this library but can't find in the readme any indication that it supports Pantone conversion.

Is this a backend-only feature of your website ?

Thanks

**Comment by epitaphmike** [comment]
@carloscabo and @damonbauer, Where did you guys get these conversions? I spoke to Pantone and they stated that the only place you can get the values is from within software and that they do not have a list available (https://twitter.com/pantone/status/492320870124109824)

If this is the case, for example in Photoshop PANTONE 186 C converts to 
Hex: #CD062E
RGB: 204, 12, 47.

I was planning on putting a DB together with this "official" information, but I am not sure what legality there would be in doing so. Thoughts?

So many sites are different.

http://rgb.to/pantone/coated/186-c
186 C     Hex: #C8102E     RGB: 200, 16, 46

http://us.labelpartners.com/pantone_coated_table.html
186 C     Hex: #C8102E     RGB: 200, 16, 46

http://www.umsiko.co.za/links/color.html
186 C     Hex: #D21034     RGB: 210, 16, 52	

http://goffgrafix.com/pantone-rgb-100.php
186 C     Hex: #CE1126     RGB: 206, 17, 38    

Though these sites give a "Max Color Distance" option to a Pantone color. I set the distance to the minimum available which is 16.
http://www.ginifab.com/feeds/pms/
http://codebeautify.org/hex-to-pantone-converter
Where the official color in the software "CD062E" gives 3 Pantone results while
rgb.to color "#C8102E" returns 2 Pantone results while
goffgrafix.com color "#CE1126" and umsiko.co.za "#D21034" only return 1, 186 C.

Needless to say there is a fair amount of difference between the listed sites, which are all top on the Google search results. 

I am going to try and get more clarification from Pantone on this in hope that we can all return unified results for the good of the interwebs.

**Comment by pixelastic** [comment]
I could not find any official pantone list, I think it is a well guarded secret from Pantone. I would be very interested in an official list as well.

**Comment by epitaphmike** [comment]
I don't know how guarded it is. From their response to me back in 2014, they said it was available in "software", ie. Photoshop or their Color Manager Software. https://twitter.com/pantone/status/492323776529321986

The strange part is in Photoshop when you select Pantone 186 C you get #CD062E, though when you select the Color from the Color palette and the Color Picker opens, it is #CC0C2F?!?!,  while in Illustrator you get #CF0A2C. Which makes me really question what Pantone is saying.

Photoshop:
![screenshot 2016-07-26 14 33 31](https://cloud.githubusercontent.com/assets/677832/17150846/0c1130c4-533f-11e6-856e-c35e84ef4e6a.png)

Illustrator:
![screenshot 2016-07-26 14 35 21](https://cloud.githubusercontent.com/assets/677832/17150861/1939c676-533f-11e6-8570-45c954cba588.png)

**Comment by epitaphmike** [comment]
I got the official Pantone® colors today directly from Pantone® that display correlating Lab, sRGB, CMYK and Hex values.

For example:
**Pantone® 186 C**
**Lab:** 44.69, 67.77, 40.06
**sRGB:** 200, 16, 46
**Hex:** #C8102E
**CMYK:** 2, 100, 85, 6

These are directly from the official Pantone® Color Matching Guide

Which means that @carloscabo is on point. Nice work.

**Comment by epitaphmike** [comment]
Looks like they added the RGB values to their site too. They didn't have them available last time I checked. https://www.pantone.com/color-finder/186-C

**Comment by ValZapod** [comment]
> So many sites are different.
> 
> http://rgb.to/pantone/coated/186-c 186 C Hex: #C8102E RGB: 200, 16, 46

That is nonsense. What RGB is that? There are infinite amount of RGB spaces. It should be sRGB 200 16 46.

>in Photoshop PANTONE 186 C converts to

Well, then it is a bug.
