### ISSUE TITLE
Add ‘rebeccapurple’?

### ISSUE THREAD

**Issue by davidhund** [carloscabo/colz#7]
Hey Carlos,
Great work on colz and rgb.to!
I noticed you allow HTML colornames on rgb.to but I found ‘rebeccapurple’ does not (yet) work. 

‘rebeccapurple’ (#336699) is a fairly new addition (21 june 2014) in memory of Rebecca Meyer (daughter of Eric Meyer) who passed away aged 12: http://lists.w3.org/Archives/Public/www-style/2014Jun/0312.html

It would be awesome if you could add ‘rebeccapurple’ to the rgb.to HTML colornames…

**Comment by carloscabo** [comment]
Hi David.
I didn't know about the story behind this color name :(

I've just added "rebeccapurple" to the html color listing:
http://rgb.to/html-color-codes/3
http://rgb.to/rebeccapurple
And also as a keyword
http://rgb.to/keywords/rebecca

I used the hex equivalency provided in the link you passed to me: #663399
Thx a lot for the advice.
Best regards.
Carlos

**Comment by davidhund** [comment]
Awesome Carlos, thanks! 
I noticed one bug: the ::before ‘swatch’ on http://rgb.to/html-color-codes/3 does not yet have the proper color background.

**Comment by carloscabo** [comment]
Hummm... I see it fine in Ch and FF... Maybe cache?
Please try reloading with a parameter in the url
http://rgb.to/html-color-codes/3?123

**Comment by davidhund** [comment]
Whoops. Heavy caching indeed. (Bad Chrome :no_good: :-))

**Comment by carloscabo** [comment]
Great! ;)
Any other issue you find please contact me.
Thx again.
